name: Build

on:
  push:
    branches:
      - feature/ci-cd-frontend

  # Allows manual execution from the GitHub Actions UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm' # Caches npm packages to speed up subsequent runs

      - name: Install Dependencies
        run: npm ci # Uses 'ci' instead of 'install' to use package-lock.json

      - name: Compile TypeScript
        run: npm run build

      - name: Upload Build Artifact
        # Passes the compiled output to the next job since runners are isolated
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
          retention-days: 1
